services:
  gpu-temp-alert:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpu-temp-alert
    environment:
      - REDPANDA_BROKERS=redpanda-1:29092,redpanda-2:29093
      - SOURCE_TOPIC=gpu-temperature
      - CONSUMER_GROUP=gpu-temp-alert-group
      - TEMPERATURE_THRESHOLD=150.0
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/---
      - SLACK_CHANNEL=#alerts
    restart: unless-stopped
    networks:
      - redpanda_network
    # Optional logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  redpanda_network:
    external: true
    name: redpanda_network  # Make sure this matches your existing network name